CREATE TABLE if not exists public.concurso_mega_sena (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	acumulado bool NOT NULL,
	dt_sorteio date NOT NULL,
	id_concurso int8 NOT NULL,
	nr_ganhadores_quadra int4 NOT NULL,
	nr_ganhadores_quina int4 NOT NULL,
	nr_ganhadores_sena int4 NOT NULL,
	pr_dezena int4 NOT NULL,
	qa_dezena int4 NOT NULL,
	qi_dezena int4 NOT NULL,
	se_dezena int4 NOT NULL,
	sx_dezena int4 NOT NULL,
	te_dezena int4 NOT NULL,
	vl_acumulado numeric(19,2) NOT NULL,
	vl_acumulado_mega_virada numeric(19,2) NULL,
	vl_arrecadacao_total numeric(19,2) NOT NULL,
	vl_estimativa_premio numeric(19,2) NULL,
	vl_rateio_quadra numeric(19,2) NOT NULL,
	vl_rateio_quina numeric(19,2) NOT NULL,
	vl_rateio_sena numeric(19,2) NOT NULL,
	id_dezenas_ordenadas int8 NULL,
	CONSTRAINT concurso_mega_sena_pkey PRIMARY KEY (id),
	CONSTRAINT uk_id_concurso UNIQUE (id_concurso)
);


-- public.concurso_mega_sena foreign keys

ALTER TABLE public.concurso_mega_sena ADD CONSTRAINT fk_id_dezenas_ordenadas FOREIGN KEY (id_dezenas_ordenadas) REFERENCES dezenas_mega_sena_ordenadas(id);



