CREATE TABLE if not exists public.cidade (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nm_cidade varchar(255) NULL,
	uf varchar(255) NULL,
	id_concurso_megasena int8 NULL,
	CONSTRAINT cidade_pkey PRIMARY KEY (id)
);

ALTER TABLE public.cidade ADD CONSTRAINT fk_id_concurso_megasena FOREIGN KEY (id_concurso_megasena) REFERENCES concurso_mega_sena(id_concurso);